- name: Add MongoDB Key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present

- name: Add MongoDB repository into sources list
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
    state: present

- name: Upate Cache
  apt:
    update_cache: yes

- name: Install MongoDB Package
  apt:
    name: mongodb-org
    state: present

- name: Update MongoDB config from Local address to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB Service
  systemd:
    name: mongod
    state: started

- name: Download schema
  unarchive:
    src: https://github.com/zelar-soft-roboshop/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Load Schema
  mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    #idempotent: yes
