- name: Install Nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: Download Frontend from Nexus
  get_url:
    url: http://172.31.14.124:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
    dest: /tmp/frontend.zip
    username: admin
    password: admin123

- name: Delete the default content
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
    - /var/www/html

- name: Create HtDocs Directory
  file:
    path: /var/www/html
    state: directory

- name: Unzip the Downloaded Content
  unarchive:
    src: /tmp/frontend.zip
    dest: /var/www/html
    remote_src: yes

- name: Update RoboShop Config file
  template:
    src: roboshop.conf
    dest: /etc/nginx/sites-enabled/roboshop.conf
  notify: Restart Nginx

- name: Start Nginx
  systemd:
    state: started
    name: nginx
    enabled: yes
