- name: Find the URL of Node_Exporter Latest Version
  shell: curl -L -s https://prometheus.io/download/  | grep tar | grep node_exporter | grep linux-amd64  | sed -e "s|>| |g" -e 's|<| |g' -e 's|"| |g' |xargs -n1 | grep ^http
  register: node_expoter_version

- name: Debug
  debug:
    msg: "{{node_expoter_version}}"




